### PR TITLE
Fix #2203 (combine with list of characters with NA)

### LINKED ISSUE #2203: combine fails to combine a list of characters with NA [with pull request: #2209]
Hi,

Thanks to everyone working on tibble, dplyr, tidyr... In general the tidyverse packages make a lot of people very happy to use R.

I have found a rather simple case where `dplyr::combine` fails, and the do.call rbind equivalent works as expected. I have tested this on the latest released dplyr and the current master (hadley/dplyr@b205d1f) versions, both showing the same error. I found this error trying to unnest a data frame using tidyr, but my C++ skills and dplyr knowledge are not good enough to fix it.

``` r
library(dplyr)
do.call(rbind,list("a", "b", "c", NA, "e")) # Works

combine(list("a", "b", "c", NA, "e")) # Does not work
#Error in eval(substitute(expr), envir, enclos) : 
#  Can not automatically convert from character to logical. 

combine(list("a", "b", "c", NA_character_, "e")) # Workaround
```

This issue affects `unnest` in tidyr:

``` r
library(tibble)
library(tidyr)

aa <- tibble(ID = list("a", "b", "c", NA, "e"))
bb <- unnest_(aa, "ID") # I would expect bb == tibble(ID = c("a", "b", "c", NA, "e"))
```

Any help will be appreciated

### PR DESCRIPTION
**Pull request by zeehio**
This rather small pull request:
- Adds a test case showing issue #2203 
- Provides a fix for #2203. This fix increases the compatibility of the character collector to tolerate logical `NA` and converting them to `NA_character_`.
- Adds the corresponding bullet to NEWS file

Any feedback will be very much appreciated

### CODE REVIEW

**Comment by krlmlr** [comment]
LGTM. Fixes #2203.

**Comment by hadley** [comment]
I wonder if it would be better to be stricter and only check for logicals of length 1?

Do we need to apply the same principle for other atomic vectors, or are they already covered? Either way, it's probably worth pulling `LGLSXP == TYPEOF(x) && all_na(x)` out into an informatively named function.

**Comment by zeehio** [comment]
Logicals with all `NA` of length > 1 also are meaningful to me:
```r
dplyr::combine(list("a", "b", "c", c(NA, NA), "e")) 
```
Should work like:
```r
dplyr::combine(list("a", "b", "c", c(NA_character_, NA_character_), "e"))
```
Returning
```r
c("a", "b", "c", NA, NA, "e")
```

I will write tests for the other collecters to check if this happens to them too and prevent regressions. I will pull `LGLSXP == TYPEOF(x) && all_na(x)` into its own function named `all_logical_na` so I can use it in other collecters if required.

**Comment by krlmlr** [comment]
```r
> combine(list(1:3, NA))
[1]  1  2  3 NA
> combine(list(1.5:3, NA))
[1] 1.5 2.5  NA
> combine(list(complex(real = 1.5:3), NA))
Error in eval(substitute(expr), envir, enclos) : 
  Can not automatically convert from complex to logical.
> combine(list(factor(1.5:3), NA))
Error in eval(substitute(expr), envir, enclos) : 
  Can not automatically convert from factor to logical.
```

**Comment by zeehio** [comment]
Test and fix if necessary that combine handles missing values with:

 - [x] logical
 - [x] integer
 - [ ] factor
 - [x] real
 - [x] character
 - [ ] POSIXct
 - [ ] Date
 - [ ] complex

```
  OK: 1609 SKIPPED: 3 FAILED: 4
  1. Error: combine works with NA and factors (#2203) (@test-combine.R#49) 
  2. Error: combine works with NA and POSIXct (#2203) (@test-combine.R#86) 
  3. Error: combine works with NA and Date (#2203) (@test-combine.R#103) 
  4. Error: combine works with NA and complex (#2203) (@test-combine.R#131) 
```

**Comment by hadley** [comment]
My main concern with checking the value for vectors > length 1 is performance since you're now scanning the value of every element. But I guess it can't actually cause a performance regression, since currently the code throws an error.

File: inst/include/dplyr/Collecter.h [hunk 1]
```diff
@@ -33,10 +37,16 @@ namespace dplyr {
     Collecter_Impl(int n_): data(n_, Rcpp::traits::get_na<RTYPE>()) {}
 
     void collect(const SlicingIndex& index, SEXP v) {
-      Vector<RTYPE> source(v);
-      STORAGE* source_ptr = Rcpp::internal::r_vector_start<RTYPE>(source);
-      for (int i=0; i<index.size(); i++) {
-        data[index[i]] = source_ptr[i];
+      if (all_logical_na(v)) {
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: I like the way Collecter<STRSXP>::collect() is split into functions with clear names.

File: inst/include/dplyr/Collecter.h [hunk 2]
```diff
@@ -295,19 +319,25 @@ namespace dplyr {
...
-      // here we can assume that v is a factor with the right levels
-      // we however do not assume that they are in the same order
-      IntegerVector source(v);
-      CharacterVector levels = source.attr("levels");
-
-      SEXP* levels_ptr = Rcpp::internal::r_vector_start<STRSXP>(levels);
-      int* source_ptr = Rcpp::internal::r_vector_start<INTSXP>(source);
-      for (int i=0; i<index.size(); i++) {
-        if (source_ptr[i] == NA_INTEGER) {
+      if (Rf_inherits(v, "factor") && has_same_levels_as(v)) {
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: Same.

**Comment by zeehio** [comment]
This still requires further work, some cases where there is an initial NA fail:

```r
combine(list(NA, "hello"))
# Error cannot convert from logical to character
``` 

Similar errors happen with factors and complex.

Solutions (I need to work on them):
- Promote logical collecter to character collecter if the logical collecter only has NA.
- Promote logical collecter to factor collecter if the logical collecter only has NA.
- Promote logical collecter to complex collecter. Would you like to convert FALSE to 0+0i and TRUE to 1+0i as well in this case?

File: inst/include/dplyr/Collecter.h [hunk 3]
```diff
@@ -9,6 +9,10 @@
 
 namespace dplyr {
 
+  static inline bool all_logical_na(SEXP x) {
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: Can we somehow reuse is_logical_all_na() below?

**Comment by krlmlr** [comment]
I think the collecter should be strict and only mix logicals with other types (including numerics) if only NAs were seen.

I remember fixing very similar issues in DelayedProcessor.h.

**Comment by zeehio** [comment]
@krlmlr,

- I hope I understood your comments in the code review. I tried to address both splitting the `collect()` function and the reuse of `is_logical_all_na()`. If I misunderstood you, please correct me again.
- If we change the collecter to be strict with respect to numbers then we break backwards compatibility. I will document this breaking change in the NEWS file.
- I still have some test cases to fix, but it's time for me to go to sleep. I will try to fix this tomorrow (in approx 20 hours).

Thanks for all your feedback, comments and suggestions

**Comment by krlmlr** [comment]
@hadley: What should `combine(list(1, TRUE, FALSE, 2))` do -- raise an error or return `c(1, 1, 0, 2)` ?

File: tests/testthat/test-combine.R [hunk 4]
```diff
@@ -16,3 +16,181 @@ test_that("combine works with input that used to fail (#1780)", {
...
+  # NA length > 1
+  works <- combine(list(as.POSIXct("2010-01-01"), as.POSIXct("2010-01-02"),
+                        c(NA, NA), as.POSIXct("2010-01-04")))
+  expect_equal(works, c(as.POSIXct(c("2010-01-01", "2010-01-02",
+                                     NA, NA, "2010-01-04"))))
+})
+
+test_that("combine works with NA and Date (#2203)", {
+  # NA first
+  expected_result <- as.Date(c(NA, "2010-01-01", "2010-01-02", NA, "2010-01-04"))
```
Comment (hadley) [inline tests/testthat/test-combine.R]: I think this would be a little easier to read if you initialised as `as.Date("2010-01-01") + c(NA, 0, 1, NA, 3)` etc

File: tests/testthat/test-combine.R [hunk 5]
```diff
@@ -16,3 +16,181 @@ test_that("combine works with input that used to fail (#1780)", {
...
+  works1 <- combine(list(NA, as.Date("2010-01-01"), as.Date("2010-01-02"),
+                         as.Date(NA), as.Date("2010-01-04")))
+  expect_equal(works1, expected_result)
```
Comment (hadley) [inline tests/testthat/test-combine.R]: I think this could just be `expect_equal(combine(as.list(works1)), works1)`

File: tests/testthat/test-combine.R [hunk 6]
```diff
@@ -16,3 +16,181 @@ test_that("combine works with input that used to fail (#1780)", {
...
+
+  works2 <- combine(list(as.Date("2010-01-01"), as.Date("2010-01-02"),
+                         NA, as.Date("2010-01-04")))
+  expect_equal(works2, expected_result)
+
+  # NA length > 1
+  expected_result <- c(as.Date(c("2010-01-01", "2010-01-02", NA, NA, "2010-01-04")))
+  works1 <- combine(list(as.Date("2010-01-01"), as.Date("2010-01-02"),
```
Comment (hadley) [inline tests/testthat/test-combine.R]: Here you could maybe make the principle easier to understand by doing `split(works1, c(1, 2, 3, 3, 4))` or similar.

File: tests/testthat/test-combine.R [hunk 7]
```diff
@@ -16,3 +16,181 @@ test_that("combine works with input that used to fail (#1780)", {
...
+
+
+test_that("combine works with NA and complex (#2203)", {
+  # NA first
+  expected_result <- c(NA, 1 + 2i)
+  works1 <- combine(list(NA, complex(real = 1, imaginary = 2)))
+  expect_equal(works1, expected_result)
+
+  # NA length == 1
+  expected_result <- complex(real = c(1, 2, NA, 4),
```
Comment (hadley) [inline tests/testthat/test-combine.R]: `c(1, 2, NA, 4) + 1i` would be more compact

**Comment by hadley** [comment]
@krlmlr For now I'd say it should be an error because we want to be strict about coercing types (integer -> double is one exception). We will need to write up the exact principles in vctrs - currently we have somewhat behaviour spread across multiple functions (i.e. https://github.com/hadley/vctrs/issues/7).

**Comment by zeehio** [comment]
- I have improved the readability of the tests following @hadley's suggestions. 
- I have added a test case that loops through all pairs of atomic types and combines them, checking that the result or error matches the expected result. Following a "strict coercing types policy" I just allow coercing NA values to anything, integers to reals, and factors to characters.
- I have fixed all the test cases dealing with combine. However I now have a test case failing:

```r
# (@test-binds.R#123)
test_that("bind_rows promotes logical to integer", {
  df1 <- data_frame(a = FALSE)
  df2 <- data_frame(a = 1L)

  res <- bind_rows(df1, df2)
  expect_equal(res$a, c(0L, 1L))
})

```

So the question now is, do we remove the coercion from logical to integer in `bind_rows` or do we use different rules in each case?

In case you decide to remove the coercion I will replace the expect_equal in the test above to an expect_error.

Before merging, the NEWS entry will need to be updated. Probably tomorrow.

File: inst/include/dplyr/Collecter.h [hunk 8]
```diff
@@ -177,11 +210,13 @@ namespace dplyr {
 
     inline bool compatible(SEXP x) {
       int RTYPE = TYPEOF(x);
-      return (INTSXP == RTYPE || RTYPE == LGLSXP) && !Rf_inherits(x, "factor");
+      return (INTSXP == RTYPE && !Rf_inherits(x, "factor") &&
+                !Rf_inherits(x, "POSIXct") && !Rf_inherits(x, "Date")) ||
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: This isn't completely failsafe against other classes such as `"difftime"`. I wonder if the additional checks here are worth the effort, or if we should just let it slide and wait for hadley/vctrs#7 (and potentially hadley/vctrs#27). @hadley?

File: NEWS.md [hunk 9]
```diff
@@ -63,6 +63,8 @@
 
 * `mutate_all()` etc now accept unnamed additional arguments.
 
+* `combine()` accepts `NA` values (#2203, @zeehio)
+
```
Comment (krlmlr) [inline NEWS.md]: Breaking changes should be documented clearly.

File: inst/include/dplyr/Collecter.h (hunk 8 above)
Comment (hadley) [inline inst/include/dplyr/Collecter.h]: I think we should probably treat any vector with a class as incompatible by default, but I agree we don't need to do that in this PR.

File: tests/testthat/test-combine.R [hunk 10]
```diff
@@ -16,3 +16,219 @@ test_that("combine works with input that used to fail (#1780)", {
...
+  expect_equal(works, c(1L, 2L, NA, 4L))
+  works <- combine(list(1L, 2L, c(NA, NA), 4L))
+  expect_equal(works, c(1L, 2L, NA, NA, 4L))
+})
+
+test_that("combine works with NA and factors (#2203)", {
+  # NA first
+  expected_result <- factor(c(NA, "a", "c", NA, "b"), levels = c("a","b","c"))
+  works1 <- combine(list(NA,
+                         factor("a", levels = c("a","b","c")),
```
Comment (zeehio) [inline tests/testthat/test-combine.R]: Done eaa9b0d10463f6d885f760187f2094a7949e1d02

File: tests/testthat/test-combine.R [hunk 11]
```diff
@@ -16,3 +16,219 @@ test_that("combine works with input that used to fail (#1780)", {
...
+  # factor and character
+  pairs$can_combine[pairs$Var1 == "factor" & pairs$Var2 == "character"] <- TRUE
+  pairs$can_combine[pairs$Var1 == "character" & pairs$Var2 == "factor"] <- TRUE
+  # Define the results that are not a trivial unlist:
+  # factor-character promotes to character
+  # factor-NA is factor (not integer)
+  # Date-NA is Date (unlist would coerce to numeric)
+  # logicalNA_POSIXct: We add tzone = ""
+  # POSIXct_POSIXct (unlist would coerce to numeric)
+  pairs_result <- list("factor_character" = c("a", "b"),
```
Comment (zeehio) [inline tests/testthat/test-combine.R]: Done 698e75023ac8b6363eb5e9238326df0050cd519c

File: inst/include/dplyr/Collecter.h (hunk 8 above)
Comment (zeehio) [inline inst/include/dplyr/Collecter.h]: I did not implement support for "difftime", but now it treats any integer or real vector with a class as incompatible (0b9ed6a257326930a3e052a29b3bdcc95e60e174) so if someone tries to collect an unsupported class (such as "difftime" or "dummyint" -in the test case-) the collecter returns an error. If you are not sure about this behaviour I can revert that and custom classes will be coerced (with potential loss of information).

File: NEWS.md (hunk 9 above)
Comment (zeehio) [inline NEWS.md]: Done in 9fb42da

File: tests/testthat/test-combine.R [hunk 12]
```diff
@@ -16,3 +16,219 @@ test_that("combine works with input that used to fail (#1780)", {
...
+  # NA length > 1
+  expected_result <- c(1, 2, NA, NA, 4) + 1i
+  expect_equal(combine(split(expected_result, c(1, 2, 3, 3, 4))),
+               expected_result)
+
+  works3 <- combine(list(1 + 1i, 2 + 1i, c(NA, NA), 4 + 1i))
+  expect_equal(works3, expected_result)
+})
+
+test_that("combine is strict combining/promoting types", {
```
Comment (zeehio) [inline tests/testthat/test-combine.R]: Sorry, I do not know how to do that and I could not find any example using testthat to guide me.

However, when I run the `test-combine.R` script the `expect_that` functions that fail print the `info` argument that contains `Pair: (item1, item2)`. This is printed when running `R CMD check`:

```
  1. Failure: combine is strict combining/promoting types (@test-combine.R#214) --
  combine(items[c(pairs$Var1[i], pairs$Var2[i])]) did not throw an error.
  Pair: ( integer , character )
```
So by reading this I know that coercing an integer and a character did not throw an error as expected (this is a dummy example, it actually gives an error)

I imagine that you would rather have `combine(items[c("integer", "character")]) did not throw an error.` as an error message, but I do not know how to do that substitution. :sweat_smile:

File: inst/include/dplyr/Collecter.h (hunk 8 above)
Comment (zeehio) [inline inst/include/dplyr/Collecter.h]: Maybe raising a warning and then coercing the class is a better solution for now (breaks less code and allows users to adapt).

I could also allow coercion from logical to integer with a warning, so the breaking change is softer. The decision is up to you. :-)

File: inst/include/dplyr/Collecter.h [hunk 13]
```diff
@@ -363,13 +427,25 @@ namespace dplyr {
         return new FactorCollecter(n, model);
       if (Rf_inherits(model, "Date"))
         return new TypedCollecter<INTSXP>(n, get_date_classes());
-      return new Collecter_Impl<INTSXP>(n);
+      if (!has_classes(model))
+        return new Collecter_Impl<INTSXP>(n);
+      else {
+        SEXP classes = Rf_getAttrib(model, R_ClassSymbol);
+        stop("Can't collect elements of class %s", CHAR(STRING_ELT(classes, 0)));
```
Comment (hadley) [inline inst/include/dplyr/Collecter.h]: I think we should make this a warning for now

File: tests/testthat/test-combine.R (hunk 12 above)
Comment (zeehio) [inline tests/testthat/test-combine.R]: I know how to do that now. Fix is on the way

**Comment by zeehio** [comment]
This is the summary of all the 11x11 = 121 possible coercions I have tested. I have considered all pairs of the following types:

- logicalvalue (logical with a non-NA value)
- logicalNA (NA)
- integer
- double
- complex
- factor
- character
- POSIXct
- Date
- num_with_class (custom numeric class, think of difftime)
- int_with_class (custom integer class)

The behaviour implemented in this PR allows to combine 35 out of 121 possible pairs.

# Allow combine with NA

Custom classes may lose attributes or have wrong attributes if a NA is present, therefore they give a warning.


|Var1           |Var2           |can_combine |warning |result                 |result_class    |
|:--------------|:--------------|:-----------|:-------|:----------------------|:---------------|
|logicalvalue   |logicalNA      |TRUE        |FALSE   |TRUE, NA               |logical         |
|logicalNA      |logicalvalue   |TRUE        |FALSE   |NA, TRUE               |logical         |
|logicalNA      |logicalNA      |TRUE        |FALSE   |NA, NA                 |logical         |
|logicalNA      |integer        |TRUE        |FALSE   |NA, 4                  |integer         |
|logicalNA      |factor         |TRUE        |FALSE   |NA, a                  |factor          |
|logicalNA      |double         |TRUE        |FALSE   |NA, 4.5                |numeric         |
|logicalNA      |character      |TRUE        |FALSE   |NA, b                  |character       |
|logicalNA      |POSIXct        |TRUE        |FALSE   |NA, 2010-01-01         |POSIXct, POSIXt |
|logicalNA      |Date           |TRUE        |FALSE   |NA, 2016-01-01         |Date            |
|logicalNA      |complex        |TRUE        |FALSE   |NA, 1+2i               |complex         |
|logicalNA      |int_with_class |TRUE        |**TRUE**   |NA, 4                  |int_with_class  |
|logicalNA      |num_with_class |TRUE        |**TRUE**   |NA, 4.5                |num_with_class  |
|integer        |logicalNA      |TRUE        |FALSE   |4, NA                  |integer         |
|factor         |logicalNA      |TRUE        |FALSE   |a, NA                  |factor          |
|double         |logicalNA      |TRUE        |FALSE   |4.5, NA                |numeric         |
|character      |logicalNA      |TRUE        |FALSE   |b, NA                  |character       |
|POSIXct        |logicalNA      |TRUE        |FALSE   |2010-01-01, NA         |POSIXct, POSIXt |
|Date           |logicalNA      |TRUE        |FALSE   |2016-01-01, NA         |Date            |
|complex        |logicalNA      |TRUE        |FALSE   |1+2i, NA               |complex         |
|int_with_class |logicalNA      |TRUE        |**TRUE**   |4, NA                  |int_with_class  |
|num_with_class |logicalNA      |TRUE        |**TRUE**   |4.5, NA                |num_with_class  |

# Allow combine with the same type

Custom classes may lose attributes and therefore give a warning.

|Var1           |Var2           |can_combine |warning |result                 |result_class    |
|:--------------|:--------------|:-----------|:-------|:----------------------|:---------------|
|logicalvalue   |logicalvalue   |TRUE        |FALSE   |TRUE, TRUE             |logical         |
|logicalNA      |logicalNA      |TRUE        |FALSE   |NA, NA                 |logical         |
|integer        |integer        |TRUE        |FALSE   |4, 4                   |integer         |
|factor         |factor         |TRUE        |FALSE   |a, a                   |factor          |
|double         |double         |TRUE        |FALSE   |4.5, 4.5               |numeric         |
|character      |character      |TRUE        |FALSE   |b, b                   |character       |
|POSIXct        |POSIXct        |TRUE        |FALSE   |2010-01-01, 2010-01-01 |POSIXct, POSIXt |
|Date           |Date           |TRUE        |FALSE   |2016-01-01, 2016-01-01 |Date            |
|complex        |complex        |TRUE        |FALSE   |1+2i, 1+2i             |complex         |
|int_with_class |int_with_class |TRUE        |**TRUE**    |4, 4                   |int_with_class  |
|num_with_class |num_with_class |TRUE        |**TRUE**    |4.5, 4.5               |num_with_class  |

# Allowed coercions

|Var1           |Var2           |can_combine |warning |result                 |result_class    |
|:--------------|:--------------|:-----------|:-------|:----------------------|:---------------|
|factor         |character      |TRUE        |**TRUE**   |a, b                   |character       |
|character      |factor         |TRUE        |FALSE   |b, a                   |character       |
|integer        |double         |TRUE        |FALSE   |4, 4.5                 |numeric         |
|double         |integer        |TRUE        |FALSE   |4.5, 4                 |numeric         |

# Not allowed combinations

|Var1           |Var2           |can_combine |warning |result                 |result_class    |
|:--------------|:--------------|:-----------|:-------|:----------------------|:---------------|
|logicalvalue   |integer        |FALSE       |FALSE   |                       |                |
|logicalvalue   |factor         |FALSE       |FALSE   |                       |                |
|logicalvalue   |double         |FALSE       |FALSE   |                       |                |
|logicalvalue   |character      |FALSE       |FALSE   |                       |                |
|logicalvalue   |POSIXct        |FALSE       |FALSE   |                       |                |
|logicalvalue   |Date           |FALSE       |FALSE   |                       |                |
|logicalvalue   |complex        |FALSE       |FALSE   |                       |                |
|logicalvalue   |int_with_class |FALSE       |FALSE   |                       |                |
|logicalvalue   |num_with_class |FALSE       |FALSE   |                       |                |
|integer        |logicalvalue   |FALSE       |FALSE   |                       |                |
|integer        |factor         |FALSE       |FALSE   |                       |                |
|integer        |character      |FALSE       |FALSE   |                       |                |
|integer        |POSIXct        |FALSE       |FALSE   |                       |                |
|integer        |Date           |FALSE       |FALSE   |                       |                |
|integer        |complex        |FALSE       |FALSE   |                       |                |
|integer        |int_with_class |FALSE       |FALSE   |                       |                |
|integer        |num_with_class |FALSE       |FALSE   |                       |                |
|factor         |logicalvalue   |FALSE       |FALSE   |                       |                |
|factor         |integer        |FALSE       |FALSE   |                       |                |
|factor         |double         |FALSE       |FALSE   |                       |                |
|factor         |POSIXct        |FALSE       |FALSE   |                       |                |
|factor         |Date           |FALSE       |FALSE   |                       |                |
|factor         |complex        |FALSE       |FALSE   |                       |                |
|factor         |int_with_class |FALSE       |FALSE   |                       |                |
|factor         |num_with_class |FALSE       |FALSE   |                       |                |
|double         |logicalvalue   |FALSE       |FALSE   |                       |                |
|double         |factor         |FALSE       |FALSE   |                       |                |
|double         |character      |FALSE       |FALSE   |                       |                |
|double         |POSIXct        |FALSE       |FALSE   |                       |                |
|double         |Date           |FALSE       |FALSE   |                       |                |
|double         |complex        |FALSE       |FALSE   |                       |                |
|double         |int_with_class |FALSE       |FALSE   |                       |                |
|double         |num_with_class |FALSE       |FALSE   |                       |                |
|character      |logicalvalue   |FALSE       |FALSE   |                       |                |
|character      |integer        |FALSE       |FALSE   |                       |                |
|character      |double         |FALSE       |FALSE   |                       |                |
|character      |POSIXct        |FALSE       |FALSE   |                       |                |
|character      |Date           |FALSE       |FALSE   |                       |                |
|character      |complex        |FALSE       |FALSE   |                       |                |
|character      |int_with_class |FALSE       |FALSE   |                       |                |
|character      |num_with_class |FALSE       |FALSE   |                       |                |
|POSIXct        |logicalvalue   |FALSE       |FALSE   |                       |                |
|POSIXct        |integer        |FALSE       |FALSE   |                       |                |
|POSIXct        |factor         |FALSE       |FALSE   |                       |                |
|POSIXct        |double         |FALSE       |FALSE   |                       |                |
|POSIXct        |character      |FALSE       |FALSE   |                       |                |
|POSIXct        |Date           |FALSE       |FALSE   |                       |                |
|POSIXct        |complex        |FALSE       |FALSE   |                       |                |
|POSIXct        |int_with_class |FALSE       |FALSE   |                       |                |
|POSIXct        |num_with_class |FALSE       |FALSE   |                       |                |
|Date           |logicalvalue   |FALSE       |FALSE   |                       |                |
|Date           |integer        |FALSE       |FALSE   |                       |                |
|Date           |factor         |FALSE       |FALSE   |                       |                |
|Date           |double         |FALSE       |FALSE   |                       |                |
|Date           |character      |FALSE       |FALSE   |                       |                |
|Date           |POSIXct        |FALSE       |FALSE   |                       |                |
|Date           |complex        |FALSE       |FALSE   |                       |                |
|Date           |int_with_class |FALSE       |FALSE   |                       |                |
|Date           |num_with_class |FALSE       |FALSE   |                       |                |
|complex        |logicalvalue   |FALSE       |FALSE   |                       |                |
|complex        |integer        |FALSE       |FALSE   |                       |                |
|complex        |factor         |FALSE       |FALSE   |                       |                |
|complex        |double         |FALSE       |FALSE   |                       |                |
|complex        |character      |FALSE       |FALSE   |                       |                |
|complex        |POSIXct        |FALSE       |FALSE   |                       |                |
|complex        |Date           |FALSE       |FALSE   |                       |                |
|complex        |int_with_class |FALSE       |FALSE   |                       |                |
|complex        |num_with_class |FALSE       |FALSE   |                       |                |
|int_with_class |logicalvalue   |FALSE       |FALSE   |                       |                |
|int_with_class |integer        |FALSE       |FALSE   |                       |                |
|int_with_class |factor         |FALSE       |FALSE   |                       |                |
|int_with_class |double         |FALSE       |FALSE   |                       |                |
|int_with_class |character      |FALSE       |FALSE   |                       |                |
|int_with_class |POSIXct        |FALSE       |FALSE   |                       |                |
|int_with_class |Date           |FALSE       |FALSE   |                       |                |
|int_with_class |complex        |FALSE       |FALSE   |                       |                |
|int_with_class |num_with_class |FALSE       |FALSE   |                       |                |
|num_with_class |logicalvalue   |FALSE       |FALSE   |                       |                |
|num_with_class |integer        |FALSE       |FALSE   |                       |                |
|num_with_class |factor         |FALSE       |FALSE   |                       |                |
|num_with_class |double         |FALSE       |FALSE   |                       |                |
|num_with_class |character      |FALSE       |FALSE   |                       |                |
|num_with_class |POSIXct        |FALSE       |FALSE   |                       |                |
|num_with_class |Date           |FALSE       |FALSE   |                       |                |
|num_with_class |complex        |FALSE       |FALSE   |                       |                |
|num_with_class |int_with_class |FALSE       |FALSE   |                       |                |

I have rebased and squashed the commits into 4 manageable commits. I will appreciate your comments.

Oh, and in case a regression appeared in the future, the error message would explicit (here is an example of what would be printed):
```
1. Failure: Coercion from factor to character (@test-combine.R#282) ----------
combine(items[c("factor", "character")]) not equal to c("a", "b").
```

**Comment by zeehio** [comment]
This has been left here ready for review, but no hurries (end of year is usually busy, so happy new year to all of you)

File: inst/include/dplyr/Collecter.h [hunk 14]
```diff
@@ -347,11 +388,34 @@ namespace dplyr {
...
+      int* source_ptr = Rcpp::internal::r_vector_start<INTSXP>(source);
+      for (int i=0; i<index.size(); i++) {
+        if (source_ptr[i] == NA_INTEGER) {
+          data[ index[i] ] = NA_INTEGER;
+        } else {
+          SEXP x = levels_ptr[ source_ptr[i] - 1 ];
+          data[ index[i] ] = levels_map.find(x)->second;
+        }
+      }
+    }
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: And here, too.

File: inst/include/dplyr/Collecter.h [hunk 15]
```diff
@@ -399,18 +475,35 @@ namespace dplyr {
...
+
     switch (TYPEOF(model)) {
     case INTSXP:
       if (Rf_inherits(model, "Date"))
         return new TypedCollecter<INTSXP>(n, get_date_classes());
       if (Rf_inherits(model, "factor"))
         return new Collecter_Impl<STRSXP>(n);
+      if (has_classes(model)) {
+        SEXP classes = Rf_getAttrib(model, R_ClassSymbol);
+        Rf_warning("Coercing class %s, with possible loss of information",
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: Coercing into what?

File: inst/include/dplyr/Collecter.h [hunk 16]
```diff
@@ -399,18 +475,35 @@ namespace dplyr {
...
+      }
       return new Collecter_Impl<INTSXP>(n);
     case REALSXP:
       if (Rf_inherits(model, "POSIXct"))
         return new POSIXctCollecter(n, Rf_getAttrib(model, Rf_install("tzone")));
       if (Rf_inherits(model, "Date"))
         return new TypedCollecter<REALSXP>(n, get_date_classes());
+      if (has_classes(model)) {
+        SEXP classes = Rf_getAttrib(model, R_ClassSymbol);
+        Rf_warning("Coercing class %s, with possible loss of information",
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: ... into what?

**Comment by krlmlr** [comment]
Oh, don't worry about the merge conflict, I can resolve it.

File: tests/testthat/test-combine.R [hunk 17]
```diff
@@ -16,3 +16,276 @@ test_that("combine works with input that used to fail (#1780)", {
...
+    } else {
+      expect_silent(res <- combine(item_pair))#,
+                   #label = paste0("combine(items[c(\"", var1, "\", \"", var2, "\")])"))
+    }
+    expect_equal(object = res,
+                 expected = result,
+                 label = paste0("combine(items[c(\"", var1, "\", \"", var2, "\")])"),
+                 expected.label = deparse(result))
+  } else {
+    expect_error(suppressWarnings(combine(item_pair)),
```
Comment (zeehio) [inline tests/testthat/test-combine.R]: `expect_error(expect_warning(...))` will not work as expected, because if a bug causes `...` to run without warnings, then `expect_warning` will raise an error that will be accepted and suppressed by `expect_error` and the test will succeed where it should have failed.

I am working on all the other comments

Comment (krlmlr) [inline tests/testthat/test-combine.R]: How about `expect_warning(expect_error(...))` ?

``` r
library(testthat)

with_reporter("summary",
  test_that("error + warning", {
    expect_warning(expect_error({warning(); stop()}))
    expect_warning(expect_error({stop()}))
    expect_warning(expect_error({warning()}))
    expect_warning(expect_error({}))
  })
)
#> ...12.34
#> Failed --------------------------------------------------------------------
#> 1. Failure: error + warning (@<text>#6) -----------------------------------
#> expect_error(...) showed 0 warnings
#> 
#> 
#> 2. Failure: error + warning (@<text>#7) -----------------------------------
#> {
#>     ...
#> } did not throw an error.
#> 
#> 
#> 3. Failure: error + warning (@<text>#8) -----------------------------------
#> {
#>     ...
#> } did not throw an error.
#> 
#> 
#> 4. Failure: error + warning (@<text>#8) -----------------------------------
#> expect_error(...) showed 0 warnings
#> 
#> 
#> DONE ======================================================================
```

**Comment by zeehio** [comment]
I have taken care of all your comments. The most noticeable change is that I decoupled `prepare_table_with_coercion_rules` from the `items` variable.

I am ready for the next round of comments if there still are any other left :+1:

File: tests/testthat/helper-combine.R [hunk 18]
```diff
@@ -0,0 +1,200 @@
...
+                integer = 4L,
+                factor = factor("a"),
+                another_factor = factor("b"),
+                double = 4.5,
+                character = "c", POSIXct = as.POSIXct("2010-01-01"),
+                Date = as.Date("2016-01-01"), complex = 1 + 2i,
+                int_with_class = structure(4L, class = "int_with_class"),
+                num_with_class = structure(4.5, class = "num_with_class"))
+
+  pairs <- prepare_table_with_coercion_rules(items)
```
Comment (krlmlr) [inline tests/testthat/helper-combine.R]: Can you define items in prepare_table_with_coercion_rules() and call that function without arguments? This probably means that we need to add a new list column "item_pair" to the pairs data frame.

File: tests/testthat/helper-combine.R [hunk 19]
```diff
@@ -0,0 +1,200 @@
...
+  }
+}
+
+prepare_table_with_coercion_rules <- function(items) {
+  special_non_vector_classes <- c("factor", "POSIXct", "Date")
+
+  can_be_combined <- function(item1, item2,
+                              class1, class2,
+                              all_na1, all_na2,
+                              known_to_dplyr1, known_to_dplyr2) {
```
Comment (krlmlr) [inline tests/testthat/helper-combine.R]: I'm not a big fan of local functions. Do they access variables other than their arguments?

**Comment by zeehio** [comment]
I will finish on Monday evening. A romantic weekend in Rome awaits me.

Thanks for all the time and reviews!

File: tests/testthat/helper-combine.R (hunk 19 above)
Comment (zeehio) [inline tests/testthat/helper-combine.R]: As you prefer, I have placed those local functions as conventional functions. :+1: 

Like you, I don't like functions that use variables out of their scope (variables other than their arguments). However I find it practical to have local functions when there is only one function that calls them (a local function, like a local variable).

As this is just a matter of taste, I have avoided using local functions as you requested :smiley:

File: tests/testthat/helper-combine.R (hunk 18 above)
Comment (zeehio) [inline tests/testthat/helper-combine.R]: Done

**Comment by krlmlr** [comment]
Thanks!
