### PR TITLE
Make mutate use collecter h

### LINKED ISSUE #1892: Integer not automatically coerced to double
This might be a won't fix, but I thought I'd float the balloon anyway.

Consider:

```
library(dplyr)
data_frame(
  id = c(1,2,3,4,5,6),
  value = c(1L,2L,3L,NA,NA,NA),
  group = c("A","A","A","B","B","B")
) %>% 
  group_by(group) %>%
  mutate(value = ifelse(is.na(value),0,value))
```

Which fails.  

Versus:

```
data_frame(
  id = c(1,2,3,4,5,6),
  value = c(1L,2L,3L,4,NA,NA),
  group = c("A","A","A","B","B","B")
) %>% 
  mutate(value = ifelse(is.na(value),0,value)) %>%
  group_by(group)
```

Which does not fail.

As a matter of linguistic parsing one might not expect different outcomes based on ordering.  Is there a reason dplyr can't coerce the returns from the group_by operation to share in the most general common data type (as done elsewhere in R) so that both functional orders yield successful results?

### PR DESCRIPTION
**Pull request by zeehio**
This PR is a continuation to #2486 and closes #1892.

`mutate(col2 = fun(col1))` on a grouped data frame calls `fun` once per group.

It used to require that `fun` returns the exact same type on each call. That is not desirable in functions that may return different (but compatible) types, such as integer and numeric.

This PR changes that behavior, so the returned vectors from each of the `fun` calls are combined using the same coercion rules than `combine` and `bind_rows`, defined in `Collecter.h`.

Comments are welcome. Feel free to be picky, so I can improve a bit my C++ and Rcpp skills. :smiley:

### CODE REVIEW

File: tests/testthat/test-binds.R [hunk 1]
```diff
@@ -457,3 +457,10 @@ test_that("bind_rows rejects data frame columns (#2015)", {
     fixed = TRUE
   )
 })
+
+test_that("bind_rows accepts difftime objects", {
```
Comment (krlmlr) [inline tests/testthat/test-binds.R]: Test case for `"hms"`:

```r
  df1 <- data.frame(x = hms::hms(hours = 1))
  df2 <- data.frame(x = as.difftime(1, units = "mins"))
  res <- bind_rows(df1, df2)
  expect_equal(res$x, hms::hms(hours = 1, minutes = 1))
```

File: inst/include/dplyr/Collecter.h [hunk 2]
```diff
@@ -364,6 +365,103 @@ namespace dplyr {
...
+    void collect(const SlicingIndex& index, SEXP v) {
+      if (Rf_inherits(v, "difftime")) {
+        collect_difftime(index, v);
+      } else if (all_logical_na(v, TYPEOF(v))) {
+        Parent::collect(index, v);
+      }
+    }
+
+    inline SEXP get() {
+      set_class(Parent::data, "difftime");
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: There is also the `"hms"` class that inherits from `"difftime"`, I guess we'd like to return `"hms"` objects if the first object is of that class.

File: inst/include/dplyr/Collecter.h [hunk 3]
```diff
@@ -364,6 +365,103 @@ namespace dplyr {
...
+        if (STRING_ELT(units, 0) == STRING_ELT(v_units,0)) {
+          Parent::collect(index, v);
+        } else {
+          // If units are different convert the existing data and the new vector
+          // to seconds (following the convention on
+          // r-source/src/library/base/R/datetime.R)
+          double factor_data = time_conversion_factor(units);
+          if (factor_data != 1.0) {
+            for (int i=0; i<Parent::data.size(); i++) {
+              Parent::data[i] = factor_data*Parent::data[i];
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: Do we need to copy the data before in-place modification?

File: inst/include/dplyr/Collecter.h [hunk 4]
```diff
@@ -364,6 +365,103 @@ namespace dplyr {
...
+            }
+          }
+          units = wrap("secs");
+          double factor_v = time_conversion_factor(v_units);
+          NumericVector v_sec(v);
+          double* v_sec_ptr = v_sec.begin();
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: This looks unsafe, better use an iterator and advance that (in addition to `i`).

File: inst/include/dplyr/Collecter.h [hunk 5]
```diff
@@ -364,6 +365,103 @@ namespace dplyr {
...
+        // assume seconds
+        v_units = wrap("secs");
+      }
+      if (units.isNULL()) {
+        // if current unit is NULL, grab the new one
+        units = v_units;
+        // then collect the data:
+        Parent::collect(index, v);
+      } else {
+        // We already units, is the new vector with the same units?
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: Please check grammar.

File: inst/include/dplyr/Collecter.h [hunk 6]
```diff
@@ -364,6 +365,103 @@ namespace dplyr {
...
+
+    void collect_difftime(const SlicingIndex& index, SEXP v) {
+      RObject v_units(Rf_getAttrib(v, Rf_install("units")));
+      if (v_units.isNULL()) {
+        // assume seconds
+        v_units = wrap("secs");
+      }
+      if (units.isNULL()) {
+        // if current unit is NULL, grab the new one
+        units = v_units;
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: Can we simply reject `"difftime"` objects that don't have a `"units"` attribute?

File: inst/include/dplyr/Collecter.h [hunk 7]
```diff
@@ -25,12 +25,13 @@ namespace dplyr {
   static bool is_class_known(SEXP x) {
     /* C++11 (need initializer lists)
     static std::set<std::string> known_classes {
-      "POSIXct", "factor", "Date", "AsIs", "integer64", "table"
+      "difftime", "POSIXct", "factor", "Date", "AsIs", "integer64", "table"
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: We shouldn't need to carry around code in comments. The old-style code also works in C++11, we'll rewrite that when we are on C++11 *and* when we touch the code again.

File: inst/include/dplyr/Gatherer.h [hunk 8]
```diff
@@ -11,341 +11,273 @@
...
-    typedef typename Rcpp::traits::storage_type<RTYPE>::type STORAGE;
-    typedef GroupedCallProxy<Data,Subsets> Proxy;
-
-    GathererImpl(RObject& first, SlicingIndex& indices, Proxy& proxy_, const Data& gdf_, int first_non_na_) :
-      gdf(gdf_), proxy(proxy_), data(gdf.nrows(), Vector<RTYPE>::get_na()), first_non_na(first_non_na_)
-    {
-      if (first_non_na < gdf.ngroups())
-        grab(first, indices);
-      copy_most_attributes(data, first);
+class Gatherer {
```
Comment (krlmlr) [inline inst/include/dplyr/Gatherer.h]: Could you please indent like the original, to make review simpler?

**Comment by krlmlr** [comment]
@zeehio: If you address the feedback here and backport to #2486, we can continue the discussion there.

**Comment by zeehio** [comment]
@krlmlr I have taken care of all the issues you mentioned. Apologies for the grammar error and for all the indentation issues, thanks for all the comments and suggestions :+1:

File: inst/include/dplyr/Collecter.h (hunk 3 above)
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: So, if a copy has been made, I'm missing it ;-)

File: inst/include/dplyr/Collecter.h [hunk 9]
```diff
@@ -364,6 +359,130 @@ namespace dplyr {
...
+          units = wrap("secs");
+          double factor_v = time_conversion_factor(v_units);
+          if (Rf_length(v) < index.size()) {
+            stop("Wrong size of vector to collect");
+          }
+          if (TYPEOF(v) == REALSXP) {
+            for (int i=0; i<index.size(); i++) {
+              Parent::data[index[i]] = factor_v * REAL(v)[i];
+            }
+          } else if (TYPEOF(v) == INTSXP) {
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: How do you create a difftime of mode integer?

File: inst/include/dplyr/Collecter.h [hunk 10]
```diff
@@ -364,6 +359,130 @@ namespace dplyr {
...
+            stop("difftime must be integer or numeric");
+          }
+        }
+      }
+    }
+
+    double time_conversion_factor(RObject v_units) {
+      // Acceptable units based on r-source/src/library/base/R/datetime.R
+      double factor = 1;
+      std::string v_units_c = Rcpp::as<std::string>(v_units);
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: I wounder if we could use a map (as a static variable in a function) that allows lookup by SEXP, both here and in has_valid_time_unit().

File: inst/include/dplyr/Collecter.h [hunk 11]
```diff
@@ -364,6 +359,130 @@ namespace dplyr {
...
+    inline bool can_promote(SEXP x) const {
+      return false;
+    }
+
+    std::string describe() const {
+      return collapse<STRSXP>(types);
+    }
+
+  private:
+    RObject units;
```
Comment (krlmlr) [inline inst/include/dplyr/Collecter.h]: Can you please move data members to the bottom?

File: inst/include/dplyr/Collecter.h (hunk 9 above)
Comment (zeehio) [inline inst/include/dplyr/Collecter.h]: I can only think of `structure(4L, units="secs", class = "difftime")` and I agree it is forcing it. I can drop the `else if` if you prefer.

File: inst/include/dplyr/Collecter.h (hunk 10 above)
Comment (zeehio) [inline inst/include/dplyr/Collecter.h]: In the last commit I used an `std::string` as key. If that is not good enough I will try to fix it tomorrow.

File: inst/include/dplyr/Collecter.h [hunk 12]
```diff
@@ -362,8 +355,139 @@ namespace dplyr {
...
+              Parent::data[index[i]] = factor_v * INTEGER(v)[i];
+            }
+          } else {
+            stop("difftime must be integer or numeric");
+          }
+        }
+      }
+    }
+
+    double time_conversion_factor(SEXP v_units) {
```
Comment (hadley) [inline inst/include/dplyr/Collecter.h]: This feels overworked to me now - I preferred the previous version with explicit if statements. Might be better to make the argument `std::string()`

File: inst/include/dplyr/Collecter.h [hunk 13]
```diff
@@ -362,8 +355,139 @@ namespace dplyr {
...
+
+      if (valid_units.find(x_units_c) != valid_units.end()) {
+        return true;
+      } else {
+        return false;
+      }
+    }
+
+    void collect_difftime(const SlicingIndex& index, SEXP v) {
+      RObject v_units(Rf_getAttrib(v, Rf_install("units")));
```
Comment (hadley) [inline inst/include/dplyr/Collecter.h]: Can't you do `v.attr("units")`? I'm pretty sure there's a C++ api here.

File: inst/include/dplyr/Collecter.h [hunk 14]
```diff
@@ -362,8 +355,139 @@ namespace dplyr {
...
+      if (v_units.isNULL()) {
+        stop("Can't collect difftime without units");
```
Comment (hadley) [inline inst/include/dplyr/Collecter.h]: I think here, and for the non REALSXP case below, you can simply do `stop("Invalid difftime object")`.

File: inst/include/dplyr/Collecter.h [hunk 15]
```diff
@@ -362,8 +355,139 @@ namespace dplyr {
...
+      std::map<std::string, double>::iterator unit_factor =
+        unit_factor_map.find(CHAR(STRING_ELT(v_units,0)));
+      if (unit_factor != unit_factor_map.end()) {
+        return unit_factor->second;
+      } else {
+        stop("Cannot convert %s to seconds", CHAR(STRING_ELT(v_units, 0)));
+      }
+    }
+
+    RObject units;
```
Comment (hadley) [inline inst/include/dplyr/Collecter.h]: Would all this code be simpler if `units` was a `std::string`?

**Comment by zeehio** [comment]
I took care of the comments, feel free to do another review if you want

**Comment by hadley** [comment]
Looks good, thanks!
