### PR TITLE
Fix NSE issues

### LINKED ISSUE #1039: Should dplyr commands gobble empty last argument?
It would be nice to allow a trailing comma in commands like the example below.  That would make it easier to rearrange the order or to comment out lines without needing to figure out whether the commas need adjusting.

```
diamonds %>%
  group_by(color, clarity) %>%
  summarise(
    depth = mean(depth),
    price = mean(price),
    carat = mean(carat),  #  <-- trailing comma here currently causes errors
  )
```

I'm imaging a function that could be called at the top of a function definition that would gobble this empty argument.  Or perhaps a wrapper function a la `Vectorize()` that could be used to convert any function into a function with this behavior.  Seems like this could be useful for many functions both within `dplyr` and elsewhere.

### LINKED ISSUE #2089: pkg::fun doesn't work in dplyr::funs
This works:

```
slci_msa_wide <- slci_msa %>%
  dplyr::select(principal_city_property, placement_care_type, value_msa) %>%
  tidyr::spread(placement_care_type, value_msa) %>%
  dplyr::left_join(
    dplyr::distinct(slci_msa, principal_city_property, pop_rank)
  ) %>%
  dplyr::arrange(-A) %>%
  dplyr::mutate(cost_rank = row_number()) %>%
  dplyr::arrange(A) %>%
  dplyr::mutate(affordability_rank = row_number()) %>%
  dplyr::select(principal_city_property, dplyr::contains("rank"), A, R, Z) %>%
  dplyr::mutate_at(dplyr::vars(A, R, Z), dplyr::funs(round)) %>%
  dplyr::mutate_at(dplyr::vars(A, R, Z), dplyr::funs(dollar))
```

But this doesn't, and the only think I changed is the last line, resulting in an error: "Error: cannot coerce type 'closure' to vector of type 'character'"

```
slci_msa_wide <- slci_msa %>%
  dplyr::select(principal_city_property, placement_care_type, value_msa) %>%
  tidyr::spread(placement_care_type, value_msa) %>%
  dplyr::left_join(
    dplyr::distinct(slci_msa, principal_city_property, pop_rank)
  ) %>%
  dplyr::arrange(-A) %>%
  dplyr::mutate(cost_rank = row_number()) %>%
  dplyr::arrange(A) %>%
  dplyr::mutate(affordability_rank = row_number()) %>%
  dplyr::select(principal_city_property, dplyr::contains("rank"), A, R, Z) %>%
  dplyr::mutate_at(dplyr::vars(A, R, Z), dplyr::funs(round)) %>%
  dplyr::mutate_at(dplyr::vars(A, R, Z), dplyr::funs(scales::dollar))
```

I think I understand why this is happening, but it causes me to violate best practice in calling functions, which is to call out the package, too.

### LINKED ISSUE #2297: Several functions (with prepending) won't work if you don't load dplyr
Because of namespace conflicts, I typically avoid `library` and instead prepend everything (e.g., either `dplyr::mutate` or `dp <- loadNamespace('dplyr')` and `dp$mutate`). If I don't want to prepend, I'll use `import` (e.g., ``import::from(magrittr, `%>%`)``). Sometimes this doesn't work because of unaccounted dependencies and such, but most of the tidyverse packages seem to work perfectly with these. The two issues I've run into so far are `dplyr::order_by` and `dplyr::data_frame`. I noticed that `dplyr::order_by` work as expected if I first run `import::from(dplyr, with_order)` and `dplyr::data_frame` will work as expected if I first run `import::from(tibble, as_tibble)`, but it would be nice if I could avoid that.

### PR DESCRIPTION
**Pull request by lionel-**
- `order_by()`, `top_n()`, `sample_n()` etc now use tidyeval. Fixes #2297.

- `funs()` now handles namespaced functions. Fixes #2089.

- depends on an rlang update where literals are not rewrapped on capture → simpler count/tally implementation. Also the last arguments of captured dots are now gobbled by default, which fixes #1039 

- bare functions are now transformed to a call in colwise functions. This allows the hybrid evaluator to kick in, and this slightly simplifies the lazy table backend. The performance issue of colwise functions is now back to where it was at the time of `mutate_each()` and `summarise_each()`: still slow with many columns, but much better than reported in #2273.

  [colwise-dplyr-purrr-nogroups.pdf](https://github.com/hadley/dplyr/files/867620/colwise-dplyr-purrr-nogroups.pdf)

### CODE REVIEW

File: R/count-tally.R [hunk 1]
```diff
@@ -59,23 +61,19 @@
...
-  # Check for NULL lazily, because `wt` could be a tidy-quoted NULL if
-  # add_tally() is called from another function (e.g. add_count())
-  n <- quo(
-    if (is_null(!! wt)) {
-      n()
-    } else {
-      sum(!! wt, na.rm = TRUE)
-    }
-  )
+  if (is_empty_quosure(wt) || is_null(f_rhs(wt))) {
```
Comment (hadley) [inline R/count-tally.R]: `quo_is_missing(wt) || quo_is_empty(wt)`?

File: R/count-tally.R [hunk 2]
```diff
@@ -59,23 +61,19 @@
...
+    n <- ~n()
```
Comment (hadley) [inline R/count-tally.R]: I think we should use `quo()` here, just to be consistent

File: R/funs.R [hunk 3]
```diff
@@ -24,15 +24,20 @@
...
 
-  names(dots) <- names2(dots)
-  missing_names <- names(dots) == ""
-  default_names <- map_chr(dots[missing_names], as_name)
-  names(dots)[missing_names] <- default_names
+new_funs <- function(funs) {
+  names(funs) <- names2(funs)
+  missing_names <- names(funs) == ""
+  default_names <- map_chr(funs[missing_names], function(dot) {
+    quo_text(node_car(f_rhs(dot)))
```
Comment (hadley) [inline R/funs.R]: Should we use `quo_name()` here?

File: R/count-tally.R (hunk 2 above)
Comment (lionel-) [inline R/count-tally.R]: I was thinking we should only use `quo()` when we need to unquote something, so this provides additional intent in the code. This rule would not apply in introductory texts.

File: R/funs.R (hunk 3 above)
Comment (lionel-) [inline R/funs.R]: I think we want to allow unquoting literal functions there.

File: R/count-tally.R (hunk 1 above)
Comment (lionel-) [inline R/count-tally.R]: that's not the naming scheme we've followed so far. It's not clear what is best to do in these cases. Same issue occurs with `set_` and `mut_` functions. Currently rlang does not type-prefix all these functions.

File: R/funs.R (hunk 3 above)
Comment (hadley) [inline R/funs.R]: Isn't this line just determining the default name?

File: R/count-tally.R (hunk 1 above)
Comment (hadley) [inline R/count-tally.R]: I thought we had been pretty consistent with a type prefix. I think it would help here.

File: R/count-tally.R (hunk 2 above)
Comment (hadley) [inline R/count-tally.R]: I think simplicity wins over the minor signal loss.

File: R/funs.R (hunk 3 above)
Comment (lionel-) [inline R/funs.R]: Yes but `quo_name()` will abort with literal inputs.

Comment (hadley) [inline R/funs.R]: Only if they're length >1 ?

File: R/count-tally.R (hunk 1 above)
Comment (lionel-) [inline R/count-tally.R]: I think these would be the very first predicates prefixed with a type in rlang.

This is linked to the issue of automatically taking the RHS in all language predicates. E.g. `is_symbol()` is shortcut for `is_symbol(f_rhs(x))`. I think this works mostly fine but is confusing because not all rlang predicates behave this way. An alternative would be a set of quosure-specific predicates. Then it probably makes sense to prefix all of them with `quo`, e.g. `quo_is_null()`, `quo_is_symbol()`.

File: R/funs.R (hunk 3 above)
Comment (lionel-) [inline R/funs.R]: oh that makes sense, `expr_name()` needs to be changed then

File: R/count-tally.R (hunk 1 above)
Comment (hadley) [inline R/count-tally.R]: What if we combined them both into `quo_is_empty()`? Then it's a specific definition of emptiness that applies primarily to quosures.

Comment (lionel-) [inline R/count-tally.R]: hmm I think we should be consistent with base R, otherwise this will be confusing.

Comment (lionel-) [inline R/count-tally.R]: > hmm I think we should be consistent with base R, otherwise this will be confusing.

maybe `is_empty_quosure()` needs to be `quo_is_missing()` then?

Comment (hadley) [inline R/count-tally.R]: Maybe it's just awkwardness in the design of `count()`: most functions would either check for missingness or `NULL`, not both. And missingness is probably what needs a special predicate.

Comment (lionel-) [inline R/count-tally.R]: these functions are definitely awkardly designed, but at least they pointed our attention to missing quosures and literal rewrapping :)
